version: '3.8'

services:
  postgre_P_hash:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: hash_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5400:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis_P_hash:
    image: redis:latest
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis1/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
